### ISSUE TITLE
Inframap not showing all of my resources in graph + square instead of name of resources

### ISSUE THREAD

**Issue by Nicolasvacher** [cycloidio/inframap#112]
Hi,
Terraform version : 13.5
Os : Alpine Linux
Provider : AWS

I'm executing this command on a tfstate containing a beanstalk env (just then env, not the app, it is already created on AWS) and an RDS database : 
`inframap generate --tfstate terraformtest.tfstate --clean=false`

It's only showing in the graph the RDS, and nothing about the Beanstalk env. 

I also have a problem with the graph created using this command : 
`inframap generate --tfstate terraform.tfstate  --clean=false | dot -Tpng > inframap.png`

Resulting in this : 
![image](https://user-images.githubusercontent.com/33927232/109976443-13292b00-7cfc-11eb-84d8-e0ad37b8fe74.png)

Any help would be greatly appreciated :) Thanks !

**Comment by xescugc** [comment]
> The squares were due to the use of the Alpine OS. Problem found for this one.

What is/was the main issue? DOT font is not present on AlpineOS? Just to know as it could be ca common usecase to run InfraMap on "minima" setup (like a CI) to generate the graph and could be good to document it or try to find a solution :)

Ok I would suggest to run `inframap generate --tfstate terraform.tfstate --raw` which will print what we are reading from the TFState, basically the `--raw` will not use any kind of logic.

On AWS the connections are detected using `security_groups` and `security_group_rules` so those 2 resources should have relations with those.

Also you can run `inframap prune --tfstate terraform.tfstate` to generate an "anonymized" (if you want even more you can add the `--canonicals` to it) so then you can send us the `tfstate` and we can check it without any leaking information. This, ofc, if you want to share it, you are free to look at the output and decide if it has any leaking information :).

**Comment by Nicolasvacher** [comment]
> What is/was the main issue? DOT font is not present on AlpineOS? 
I don't know, I installed graphviz, got dot, but it wasn't writing it correctly, so i tried on a CentOS and it worked. 

> Ok I would suggest to run inframap generate --tfstate terraform.tfstate --raw
I tried it yes, but ran into an error, something like "graph node already exist" for one of my resources (not AWS but in the same tf code). 

> On AWS the connections are detected using security_groups and security_group_rules so those 2 resources should have relations with those.
So that's why my PG and NLB are not connected together ? 

Of course, how can I send it to you ? Here ? Private ? 

Thanks

**Comment by xescugc** [comment]
> Of course, how can I send it to you ? Here ? Private ?

Whatever is more confortable for you :) I would prefer it on the issue as with the `prune` we remove any sensible information (most of the test are real tfstates through the `prune`) and we keep the one we need.

But if you prefer you can email me :) (info on GH profile :+1: )

Potentially the main issue is that there is no connection between those 2 resources, could you also explain me (in case I don't see anything on the State) what resource should be connecting those 2 elements in your opinion?

Also, if you use more than 1 module on your TFState then https://github.com/cycloidio/inframap/pull/111 could be the issue (for what I see that you say when you use the `--raw`)

**Comment by ziyi-bear** [comment]
Hello, I used gitlab-ci, and use the image provide: `cycloid/inframap` also face this issue
```
variables:
  INFRAMAP_EXPORT_FILE_PREFIX: "inframap_export_"
  INFRAMAP_EXPORT_FILENAME_STD: "std"
  INFRAMAP_EXPORT_FILENAME_CONNECTIONS: "connections"
  INFRAMAP_EXPORT_FILENAME_RAW: "raw"

terraform-inframap:
  stage: build
  tags:
    - docker
    - linux
  image:
    name: cycloid/inframap
    entrypoint: [""]
  variables:
    INFRAMAP_EXTRA_ARGS: "--hcl --clean=false"
  before_script:
    - export PATH=/app:$PATH
    - inframap version
   
    - apk add graphviz
  script:
    - cd ${TF_ROOT}
    ## https://unix.stackexchange.com/questions/31947/how-to-add-a-newline-to-the-end-of-a-file
    ## add a newline to the end of a file
    - sed -i -e '$a\' *.tf 
    - cat *.tf > temp_inframap.tf

    - cat temp_inframap.tf

    - inframap generate temp_inframap.tf ${INFRAMAP_EXTRA_ARGS} | dot -Tpng > ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}.png

    - inframap generate --connections=false temp_inframap.tf ${INFRAMAP_EXTRA_ARGS} | dot -Tpng > ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}.png

    - inframap generate temp_inframap.tf --raw ${INFRAMAP_EXTRA_ARGS} | dot -Tpng > ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}.png
  artifacts:
    paths:
      - "temp_inframap.tf"
      - "inframap*.png"
    untracked: false
    expire_in: 90 days

## https://stackoverflow.com/questions/52928915/cant-share-global-variable-value-between-jobs-in-gitlab-ci-yaml-file
terraform-inframap-upload:
  stage: .post
  tags:
    - docker
    - linux
  needs:
    - job: terraform-inframap
      artifacts: true
  image: curlimages/curl
  before_script:
    - curl --version
    - echo "ls:" $(ls -la)
    - echo "Upload inframap std File Name:" ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}
    - echo "Upload inframap connections File Name:" ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}
    - echo "Upload inframap raw File Name:" ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}
  script:
    - cd ${REPORT_FOLDER} && ls -la 
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -H "Expect:" --upload-file ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}.png "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/IaC-Report/${CI_COMMIT_REF_NAME}/${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}.png" '
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -H "Expect:" --upload-file ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}.png "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/IaC-Report/${CI_COMMIT_REF_NAME}/${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}.png" '
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -H "Expect:" --upload-file ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}.png "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/IaC-Report/${CI_COMMIT_REF_NAME}/${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}.png" '
```

the image generate use the cicd as followed 

![inframap_export_raw (1)](https://user-images.githubusercontent.com/54978757/165656254-c3db4a29-a05e-48fd-b385-fc6ff0bc4e9b.png)
![inframap_export_std (1)](https://user-images.githubusercontent.com/54978757/165656257-39ca64b4-a582-48f2-880a-bfa9719bbed1.png)
![inframap_export_connections (1)](https://user-images.githubusercontent.com/54978757/165656259-36cd5b1a-b601-497e-9052-d9914a792e0b.png)

How can i fixed it? thanks

**Comment by xescugc** [comment]
Hi @ziyi-bear could you send me https://github.com/cycloidio/inframap/issues/112#issuecomment-793875058?

I may deduce that the resoruce you have we do not support connections for them, right now we'll only display (on AWS) connections by SecurityGroups. So if in you usecase there are not it's better of potentially using the `--raw` or you could use `--connections=false` (without the `--raw`) which will improve a bit the output I think.

**Comment by bollohz** [comment]
Hello there, 

I've used successfully Inframap inside a GitLab CI pipeline. 
It seems that inside the Alpine Docker image some fonts are missing you can find some details here: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11144

I've added this script inside my CI Pipeline and everything works fine: 

`
  before_script:
    - export PATH=/app:$PATH
    - inframap version
    - apk add graphviz
    - apk add font-bitstream-type1 ghostscript-fonts ttf-cantarell
`

**Comment by xescugc** [comment]
Ou! Really good find @bollohz hehe

@Nicolasvacher and @ziyi-bear could you test what @bollohz mentioned to see if it works?

I'll also test it on my side with the Docker image and if it fails I think the solution would be for us to add those pkgs on the builded image.

**Comment by ziyi-bear** [comment]
> Hello there,
> 
> I've used successfully Inframap inside a GitLab CI pipeline. It seems that inside the Alpine Docker image some fonts are missing you can find some details here: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11144
> 
> I've added this script inside my CI Pipeline and everything works fine:
> 
> ```
>   before_script:
>     - export PATH=/app:$PATH
>     - inframap version
>     - apk add graphviz
>     - apk add font-bitstream-type1 ghostscript-fonts ttf-cantarell
> ```

YES I have Test it and this setting works, thanks @bollohz 

My Project Output, although the image is a little long
![inframap_export_connections (5)](https://user-images.githubusercontent.com/54978757/187864962-7e0becc9-c625-476a-9ead-6a0fb551e035.png)

**Comment by ziyi-bear** [comment]
> Ou! Really good find @bollohz hehe
> 
> @Nicolasvacher and @ziyi-bear could you test what @bollohz mentioned to see if it works?
> 
> I'll also test it on my side with the Docker image and if it fails I think the solution would be for us to add those pkgs on the builded image.

This is my gitlab ci file: `inframap.gitlab-ci.yml`

```yaml
variables:
  INFRAMAP_EXPORT_FILE_PREFIX: "inframap_export_"
  INFRAMAP_EXPORT_FILENAME_STD: "std"
  INFRAMAP_EXPORT_FILENAME_CONNECTIONS: "connections"
  INFRAMAP_EXPORT_FILENAME_RAW: "raw"

terraform-inframap:
  stage: build
  tags:
    - docker
    - linux
  image:
    name: cycloid/inframap
    entrypoint: [""]
  variables:
    INFRAMAP_EXTRA_ARGS: "--hcl --clean=false"
  before_script:
    - export PATH=/app:$PATH
    - inframap version
    - apk add graphviz
    - apk add font-bitstream-type1 ghostscript-fonts ttf-cantarell
  script:
    - cd ${TF_ROOT}
    ## https://unix.stackexchange.com/questions/31947/how-to-add-a-newline-to-the-end-of-a-file
    ## add a newline to the end of a file
    - sed -i -e '$a\' *.tf 
    - cat *.tf > temp_inframap.tf
    - cat temp_inframap.tf
    - inframap generate temp_inframap.tf ${INFRAMAP_EXTRA_ARGS} | dot -Tpng > ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}.png
    - inframap generate --connections=false temp_inframap.tf ${INFRAMAP_EXTRA_ARGS} | dot -Tpng > ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}.png
    - inframap generate temp_inframap.tf --raw ${INFRAMAP_EXTRA_ARGS} | dot -Tpng > ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}.png
  artifacts:
    paths:
      # - "temp_inframap.tf"
      - "inframap*.png"
    untracked: false
    expire_in: 90 days

## https://stackoverflow.com/questions/52928915/cant-share-global-variable-value-between-jobs-in-gitlab-ci-yaml-file
terraform-inframap-upload:
  stage: .post
  tags:
    - docker
    - linux
  needs:
    - job: terraform-inframap
      artifacts: true
  image: curlimages/curl
  before_script:
    - curl --version
    - echo "ls:" $(ls -la)
    - echo "Upload inframap std File Name:" ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}
    - echo "Upload inframap connections File Name:" ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}
    - echo "Upload inframap raw File Name:" ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}
  script:
    - cd ${REPORT_FOLDER} && ls -la 
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -H "Expect:" --upload-file ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}.png "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/IaC-Report/${CI_COMMIT_REF_NAME}/${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_STD}.png" '
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -H "Expect:" --upload-file ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}.png "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/IaC-Report/${CI_COMMIT_REF_NAME}/${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_CONNECTIONS}.png" '
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" -H "Expect:" --upload-file ${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}.png "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/IaC-Report/${CI_COMMIT_REF_NAME}/${INFRAMAP_EXPORT_FILE_PREFIX}${INFRAMAP_EXPORT_FILENAME_RAW}.png" '
```

@xescugc It will generate the image and save to gitlab repo package

![image](https://user-images.githubusercontent.com/54978757/187866217-70f26e5c-7bca-4b04-9edd-83f6e7ae3535.png)
![image](https://user-images.githubusercontent.com/54978757/187866309-3f5c7790-5162-4816-b724-46acc1702bde.png)
